[language-server.ruby-lsp]
command = "ruby-lsp"

[[language]]
name = "ruby"
language-servers = ["ruby-lsp"]
rulers = [140]

[[language]]
name = "c-sharp"
rulers = []

[[language]]
name = "typescript"
rulers = [120]

[[language]]
name = "markdown"
rulers = []
