#!/bin/bash

date_fmt=$(date +'%a %d %b %H:%M %p')
bat=$(upower -d | grep -E percentage | awk 'NR <= 2 { print $2 }' | paste -d' ' -s)
status=$(cat /sys/class/power_supply/BAT0/status)
song=$(get_song)
vol=$(pactl list sinks | rg '\d{1,3}%' --only-matching | head -n1)

printf "%s • ♪ %s • %s %s • %s\n" "$song" "$vol" "$status" "$bat" "$date_fmt"
