#!/bin/sh

# Terminate already running bar instances
killall polybar

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

pgrep -x ssh-agent > /dev/null || eval `ssh-agent`
pgrep -x sxhkd > /dev/null || sxhkd &
setxkbmap -layout us -variant altgr-intl -option compose:ralt
xsetroot -cursor_name left_ptr &
nitrogen --set-tiled ~/Images/Ashim DSilva.jpg
nm-applet &
polybar --reload desk &
/usr/libexec/geoclue-2.0/demos/agent &
/usr/bin/redshift -P -O 6000:3000 -m randr:screen=0,1 &
xset r rate 400 30
pgrep -x ulauncher || ulauncher --no-window-shadow --hide-window &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         4
bspc config window_gap           0
bspc config focused_border_color \#285577
bspc config normal_border_color  \#282828

bspc config split_ratio            0.52
bspc config borderless_monocle     false
bspc config gapless_monocle        false
bspc config focus_follows_pointer  true

bspc rule -a Spotify desktop='^6' state=pseudo_tiled
bspc rule -a mpv desktop='^5'
bspc rule -a Slack desktop='^7' state=pseudo_tiled
bspc rule -a mupdf-x11 state=pseudo_tiled
bspc rule -a Matplotlib state=floating
bspc rule -a Emacs state=tiled
