#! /bin/sh

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

pgrep -x sxhkd > /dev/null || sxhkd &
setxkbmap -option caps:escape -option compose:rctrl -layout gb &
xsetroot -cursor_name left_ptr &
nitrogen --set-scaled ~/Images/Graphite.jpg &
nm-applet &
polybar --reload main &
redshift -P -O 5500 &
# pgrep bspswallow || bspswallow &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap           4
bspc config focused_border_color \#3c3836
bspc config normal_border_color  \#1d2021

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config focus_follows_pointer true

bspc rule -a 'Firefox Developer Edition' desktop='^2'
bspc rule -a Spotify desktop='^6' state=pseudo_tiled
bspc rule -a mpv desktop='^5'
bspc rule -a Slack desktop='^7' state=pseudo_tiled
bspc rule -a mupdf-x11 state=pseudo_tiled
bspc rule -a Matplotlib state=floating

