vim.cmd [[packadd packer.nvim]]

return require('packer').startup(function()
  use 'wbthomason/packer.nvim'

  use 'AndrewRadev/splitjoin.vim'
  use 'airblade/vim-gitgutter'
  use 'airblade/vim-rooter'
  use 'andreypopp/vim-colors-plain'
  use 'axvr/org.vim'
  use 'jiangmiao/auto-pairs'
  use 'justinmk/vim-dirvish'
  use 'lambdalisue/gina.vim'
  use 'ledger/vim-ledger'
  use 'neovim/nvim-lspconfig'
  use 'norcalli/snippets.nvim'
  use 'nvim-lua/completion-nvim'
  use 'nvim-lua/plenary.nvim'
  use 'nvim-lua/popup.nvim'
  use 'nvim-telescope/telescope.nvim'
  use 'nvim-treesitter/nvim-treesitter'
  use 'plasticboy/vim-markdown'
  use 'sheerun/vim-polyglot'
  use 'tpope/vim-abolish'
  use 'tpope/vim-commentary'
  use 'tpope/vim-sleuth'
  use 'tpope/vim-surround'
  use 'tpope/vim-unimpaired'
  use 'wincent/loupe'
end)
