local wezterm = require("wezterm")

return {
  {
    key = "q",
    mods = "LEADER|CTRL",
    action = wezterm.action({ SendKey = { key = "q", mods = "LEADER|CTRL" } }),
  },
  {
    key = '"',
    mods = "LEADER|SHIFT",
    action = wezterm.action({ SplitVertical = { domain = "CurrentPaneDomain" } }),
  },
  {
    key = "%",
    mods = "LEADER|SHIFT",
    action = wezterm.action({ SplitHorizontal = { domain = "CurrentPaneDomain" } }),
  },
  { key = "z", mods = "LEADER", action = "TogglePaneZoomState" },
  { key = "a", mods = "LEADER", action = "ActivateLastTab" },
  { key = "c", mods = "LEADER", action = wezterm.action({ SpawnTab = "CurrentPaneDomain" }) },
  { key = "p", mods = "LEADER", action = wezterm.action({ ActivateTabRelative = -1 }) },
  { key = "p", mods = "LEADER|CTRL", action = wezterm.action({ ActivateTabRelative = -1 }) },
  { key = "n", mods = "LEADER", action = wezterm.action({ ActivateTabRelative = 1 }) },
  { key = "n", mods = "LEADER|CTRL", action = wezterm.action({ ActivateTabRelative = 1 }) },
  { key = "h", mods = "LEADER", action = wezterm.action({ ActivatePaneDirection = "Left" }) },
  {
    key = "h",
    mods = "LEADER|CTRL",
    action = wezterm.action({ ActivatePaneDirection = "Left" }),
  },
  { key = "j", mods = "LEADER", action = wezterm.action({ ActivatePaneDirection = "Down" }) },
  {
    key = "j",
    mods = "LEADER|CTRL",
    action = wezterm.action({ ActivatePaneDirection = "Down" }),
  },
  { key = "k", mods = "LEADER", action = wezterm.action({ ActivatePaneDirection = "Up" }) },
  { key = "k", mods = "LEADER|CTRL", action = wezterm.action({ ActivatePaneDirection = "Up" }) },
  { key = "l", mods = "LEADER", action = wezterm.action({ ActivatePaneDirection = "Right" }) },
  {
    key = "l",
    mods = "LEADER|CTRL",
    action = wezterm.action({ ActivatePaneDirection = "Right" }),
  },
  { key = "1", mods = "LEADER", action = wezterm.action({ ActivateTab = 0 }) },
  { key = "2", mods = "LEADER", action = wezterm.action({ ActivateTab = 1 }) },
  { key = "3", mods = "LEADER", action = wezterm.action({ ActivateTab = 2 }) },
  { key = "4", mods = "LEADER", action = wezterm.action({ ActivateTab = 3 }) },
  { key = "5", mods = "LEADER", action = wezterm.action({ ActivateTab = 4 }) },
  { key = "6", mods = "LEADER", action = wezterm.action({ ActivateTab = 5 }) },
  { key = "7", mods = "LEADER", action = wezterm.action({ ActivateTab = 6 }) },
  { key = "8", mods = "LEADER", action = wezterm.action({ ActivateTab = 7 }) },
  { key = "9", mods = "LEADER", action = wezterm.action({ ActivateTab = 8 }) },
  {
    key = "&",
    mods = "LEADER|SHIFT",
    action = wezterm.action({ CloseCurrentTab = { confirm = true } }),
  },
  {
    key = "d",
    mods = "LEADER",
    action = wezterm.action({ CloseCurrentPane = { confirm = true } }),
  },
  {
    key = "x",
    mods = "LEADER",
    action = wezterm.action({ CloseCurrentPane = { confirm = true } }),
  },
  {
    key = "[",
    mods = "LEADER",
    action = wezterm.action.ActivateCopyMode,
  },
  { key = "]", mods = "LEADER", action = wezterm.action.PasteFrom("Clipboard") },
  { key = "w", mods = "LEADER", action = wezterm.action.ShowTabNavigator },
}
