#!/bin/bash

base_dir="/sys/class/backlight/intel_backlight"
old_brightness_value=$(< "$base_dir/brightness")
max_brightness_value=$(< "$base_dir/max_brightness")

add=$1
new_brightness=$((old_brightness_value + ${add:=0}))
sudo echo $new_brightness > "$base_dir/brightness"
