#!/bin/bash

base_dir="/sys/class/backlight/intel_backlight"
old_brightness_value=$(< "$base_dir/brightness")
max_brightness_value=$(< "$base_dir/max_brightness")

add=$1
new_brightness=$((old_brightness_value + ${add:=0}))
if ((new_brightness < 0)); then
  new_brightness=0
fi
if ((new_brightness > max_brightness_value)); then
  new_brightness=$max_brightness_value
fi
echo $new_brightness | sudo tee "$base_dir/brightness"
