#!/bin/bash

# Uses the first available player e.g. firefox, spotify...
# playerctl -p metadata --format '{{artist}} -- {{title}}'
status=$(playerctl -p status)
song="{{artist}} — {{title}}"

format() {
  playerctl metadata --format "$1"
}

if [ "$status" = "" ]
then
  echo "No players found"
fi
if [ "$status" == "Paused" ]
then
  echo $(format "(Paused) $song")
else
  echo $(format "$song")
fi
