#!/bin/bash

options="suspend\nlock\nreboot\nshut down"
choice="$(echo -e $options | dmenu -fn 'Dank Mono')"

case "$choice" in
  suspend) systemctl suspend;;
  lock) bspc quit;;
  reboot) reboot;;
  "shut down") poweroff;;
esac
