(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(adwaita-dark-theme-mode-line-padding 2)
 '(custom-enabled-themes '(adwaita-dark))
 '(custom-safe-themes t)
 '(elfeed-feeds
   '(("https://github.com/emacs-mirror/emacs/commits.atom")
     ("https://www.winstonhearn.com/index.xml")
     ("https://blog.phundrak.com/index.xml")
     ("https://journal.stuffwithstuff.com/rss.xml")
     ("https://intuitiveexplanations.com/feed.xml")
     ("https://www.jefftk.com/news.rss")
     ("https://www.justingarrison.com/index.xml")
     ("https://blog.meain.io/feed.xml")
     ("https://www.mattkeeter.com/atom.xml")
     ("https://cestlaz.github.io/rss.xml")
     ("https://irreal.org/blog/?feed=rss2")
     ("https://tony-zorman.com/atom.xml")
     ("https://emacsair.me/feed.xml")
     ("https://dudemanguy.github.io/blog/rss.xml")
     ("https://codeberg.org/dnkl/foot.rss")
     ("https://feeds.transistor.fm/on-the-metal-0294649e-ec23-4eab-975a-9eb13fd94e06")
     ("https://perso.pw/lambda/feed.xml")
     ("https://unixsheikh.com/feed.rss")
     ("https://christine.website/blog.rss")
     ("https://drewdevault.com/blog/index.xml")
     ("https://emersion.fr/blog/atom.xml")
     ("https://seirdy.one/posts/index.xml")
     ("https://yaah.dev/feed.xml")
     ("https://jae.moe/blog/index.xml")
     ("https://peppe.rs/index.xml")
     ("https://blog.sulami.xyz/atom.xml")
     ("https://phaazon.net/blog/feed")
     ("https://rachelbythebay.com/w/atom.xml")
     ("https://notes.eatonphil.com/rss.xml")
     ("https://huonw.github.io/blog/atom.xml")
     ("https://bicompact.space/feeds/all.rss.xml")
     ("https://cosine.blue/rss.xml")
     ("https://notes.yukiisbo.red/feed.xml")
     ("https://64k.space/feed.xml")
     ("https://blog.brownplt.org/feed.xml")
     ("https://lambdaland.org/index.xml")
     ("https://noteflakes.com/feeds/rss")
     ("https://blog.nindalf.com/index.xml")
     ("https://eclair.cafe/blog/index.xml")
     ("https://ardentperf.com/feed/")
     ("https://jcs.org/rss")
     ("https://www.benkuhn.net/index.xml")
     ("https://blog.nelhage.com/atom.xml")
     ("https://harelang.org/blog/index.xml")
     ("https://briancallahan.net/blog/feed.xml")
     ("https://typesanitizer.com/blog/rss.xml")
     ("https://microservices.io/feed.xml")
     ("https://hirrolot.github.io/rss.xml")
     ("https://leahneukirchen.org/blog/index.atom")
     ("https://0pointer.net/blog/index.atom")
     ("https://benjamincongdon.me/blog/feed.xml")
     ("https://tomcritchlow.com/feed")
     ("https://vale.dev/rss.xml")
     ("https://brooker.co.za/blog/atom.xml")
     ("https://autodidacts.io/rss/")
     ("https://meribold.org/feed.xml")
     ("https://www.arp242.net/feed.xml")
     ("https://notes.volution.ro/index.xml")
     ("https://theevilskeleton.gitlab.io/feed.xml")
     ("https://arrdem.com/feeds/all.xml")
     ("https://stevelosh.com/rss.xml")
     ("http://cdaniels.net/feed_http.atom")
     ("http://peter.eisentraut.org/feed.xml")
     ("https://bsago.me/tech-notes/feed.atom")
     ("https://susam.net/blog/feed.xml")
     ("https://blog.ysndr.de/atom.xml")
     ("https://amodernist.com/all.atom")
     ("https://tilde.town/~ramin_hal9001/atom.xml")
     ("https://github.com/googlefonts/Inconsolata/commits.atom")
     ("https://github.com/neovim/neovim/commits.atom")
     ("https://github.com/swaywm/sway/commits.atom")
     ("https://github.com/tmux/tmux/commits.atom")
     ("https://gitlab.freedesktop.org/wlroots/wlroots/-/commits/master?format=atom")
     ("https://emacsredux.com/atom.xml")
     ("https://www.murilopereira.com/index.xml")
     ("https://protesilaos.com/codelog.xml")
     ("https://thesephist.com/index.xml")
     ("https://danluu.com/atom.xml")
     ("https://blog.nightly.mozilla.org/feed/")
     ("https://hacks.mozilla.org/feed/")
     ("https://blogs.gnome.org/alexl/feed/")
     ("https://lobste.rs/t/linux,vim,systemd,vcs,unix,show.rss")
     ("https://sachachua.com/blog/category/emacs-news/feed")
     ("https://this-week-in-rust.org/rss.xml")
     ("https://lwn.net/headlines/rss")
     ("https://protesilaos.com/news.xml")
     ("https://cprss.s3.amazonaws.com/rubyweekly.com.xml")
     ("https://sizeof.cat/atom.xml")
     ("https://sirupsen.com/atom.xml")
     ("https://ghedam.at/feed")
     ("https://ianthehenry.com/feed.xml")
     ("https://github.com/BurntSushi/ripgrep/releases.atom")
     ("https://github.com/JetBrains/JetBrainsMono/releases.atom")
     ("https://github.com/alacritty/alacritty/releases.atom")
     ("https://github.com/be5invis/Iosevka/releases.atom")
     ("https://github.com/cli/cli/releases.atom")
     ("https://github.com/cormullion/juliamono/releases.atom")
     ("https://github.com/googlefonts/Inconsolata/releases.atom")
     ("https://github.com/junegunn/fzf/releases.atom")
     ("https://github.com/swaywm/sway/releases.atom")
     ("https://github.com/swaywm/swaybg/releases.atom")
     ("https://github.com/swaywm/swayidle/releases.atom")
     ("https://github.com/swaywm/wlroots/releases.atom")
     ("https://github.com/docker/compose/releases.atom")
     ("https://github.com/ajeetdsouza/zoxide/releases.atom")
     ("https://github.com/Cloudef/bemenu/releases.atom")
     ("https://github.com/tonsky/FiraCode/releases.atom")
     ("https://www.ruby-lang.org/en/feeds/news.rss")
     ("https://github.com/VirtusLab/git-machete/releases.atom")
     ("https://github.com/fish-shell/fish-shell/releases.atom")
     ("https://archlinux.org/feeds/news/")
     ("https://www.possiblerust.com/feed.xml")
     ("https://riotarttherite.tumblr.com/rss")
     ("https://spacepub.space/feeds/videos.atom?videoChannelId=2")
     ("http://c2.com/cgi/wikiRss?min=0&days=.2")
     ("https://thoughtbot.com/blog/feed.xml")
     ("https://thume.ca/atom.xml")
     ("https://thesquareplanet.com/feed.xml")
     ("https://www.charlieharrington.com/rss.xml")
     ("https://bernsteinbear.com/feed.xml")
     ("https://metaredux.com/feed.xml")
     ("https://raphlinus.github.io/feed.xml")
     ("https://karl-voit.at/feeds/lazyblorg-all.atom_1.0.links-and-content.xml")
     ("https://icyphox.sh/blog/feed.xml")
     ("https://fasterthanli.me/index.xml")
     ("https://blog.burntsushi.net/index.xml")
     ("https://michael.stapelberg.ch/feed.xml")
     ("https://alexandrabac.blogspot.com/feeds/posts/default")
     ("https://based.cooking/atom.xml")
     ("https://adnano.co/atom.xml")
     ("https://zverok.github.io/feed.xml")
     ("https://www.getrevue.co/profile/theprincessxena.rss")
     ("http://dtrace.org/blogs/bmc/feed/")
     ("https://armaanb.net/feed")
     ("https://work.lisk.in/atom.xml")
     ("https://tsdh.org/rss.xml")))
 '(isearch-allow-motion t)
 '(org-export-backends '(ascii html icalendar latex md odt))
 '(package-selected-packages
   '(tide flycheck orderless vertico-directory adwaita-dark-theme tree-sitter-indent doom-themes inf-ruby vertico corfu marginalia fd-dired ligature forge eglot password-store zig-mode json-mode diff-hl sudo-utils graphviz-dot-mode auto-package-update edit-indirect typescript-mode rg yaml-mode vterm rust-mode tree-sitter-hl tree-sitter-langs tree-sitter expand-region elfeed magit rainbow-delimiters paredit markdown-mode))
 '(warning-suppress-types '((lsp-mode) (lsp-mode))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
